MiSegundaAplicacionWeb/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiPrimeraAplicacionWeb.Models
{
    public class Curso
    {
        public int IIDCURSO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string BHABILITADO { get; set; }

    }
}

MiSegundaAplicacionWeb/Models/Periodo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiSegundaAplicacionWeb.Models
{
    public class Periodo
    {
        public int IIDPERIODO { get; set; }
        public string NOMBRE { get; set; }
        public DateTime FECHAINICIO { get; set; }
        public DateTime FECHAFIN { get; set; }
        public int BHABILITADO { get; set; }
    }
}

MiSegundaAplicacionWeb/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiSegundaAplicacionWeb.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult listarSexo()
        {
            PruebaDataContext bd = new PruebaDataContext();
            var lista = (bd.Sexo.Where(p => p.BHABILITADO.Equals(1))
                .Select(p => new { IID= p.IIDSEXO, p.NOMBRE })).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }





        public JsonResult listarAlumnos()
        {
            PruebaDataContext bd = new PruebaDataContext();
            var lista = (bd.Alumno.Where(p => p.BHABILITADO.Equals(1))
                .Select(p => new { p.IIDALUMNO,p.NOMBRE,p.APPATERNO,p.APMATERNO,p.TELEFONOPADRE })).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }
    }
}

MiSegundaAplicacionWeb/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiSegundaAplicacionWeb.Controllers
{
    public class CursoController : Controller
    {
        // GET: Curso
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult listarcurso()
        {
            PruebaDataContext bd = new PruebaDataContext();
            var lista = bd.Curso.Where(p => p.BHABILITADO.Equals(1))
                .Select(p => new { p.IIDCURSO, p.NOMBRE, p.DESCRIPCION });
            return Json(lista,JsonRequestBehavior.AllowGet);
        }
        public JsonResult BuscarCursoPorNombre(string nombre)
            {

            PruebaDataContext bd = new PruebaDataContext();
            var lista = bd.Curso.Where(p => p.BHABILITADO.Equals(1)&& p.NOMBRE.Contains(nombre))
                .Select(p => new { p.IIDCURSO, p.NOMBRE, p.DESCRIPCION });
            return Json(lista, JsonRequestBehavior.AllowGet);
        }
    }
}

MiSegundaAplicacionWeb/Controllers/PeriodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiSegundaAplicacionWeb.Controllers
{
    public class PeriodoController : Controller
    {
        // GET: Periodo
        public ActionResult Index()
        {
            return View();
        }
        public string mensaje()
        {
            return "HOy es un lindo dia muchas gracias Universo";
        }
        public JsonResult listarperiodo()
        {
            PruebaDataContext bd = new PruebaDataContext();
            var lista = (bd.Periodo.Where(p => p.BHABILITADO.Equals(1))
            .Select(p => new {p.IIDPERIODO, p.NOMBRE,FECHAINICIO=((DateTime) p.FECHAINICIO).ToShortDateString(),FECHAFIN =((DateTime)p.FECHAFIN).ToShortDateString() }));
            return Json(lista, JsonRequestBehavior.AllowGet);

        }
        public JsonResult BuscarPeriodoPorNombre(string nombre)
        {
            PruebaDataContext bd = new PruebaDataContext();
            var lista = (bd.Periodo.Where(p => p.BHABILITADO.Equals(1)&& p.NOMBRE.Contains(nombre))
            .Select(p => new { p.IIDPERIODO, p.NOMBRE, FECHAINICIO = ((DateTime)p.FECHAINICIO).ToShortDateString(), FECHAFIN = ((DateTime)p.FECHAFIN).ToShortDateString() }));
            return Json(lista, JsonRequestBehavior.AllowGet);

        }
    }
}

MiSegundaAplicacionWeb/Controllers/SeccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiSegundaAplicacionWeb.Controllers
{
    public class SeccionController : Controller
    {
        // GET: Seccion
        public ActionResult Inicio()
        {
            return View();
        }
    }
}

MiSegundaAplicacionWeb/Views/Alumno/Index.cshtml
@{
    ViewBag.Title = "Index";
}

    <link href="~/Content/datatables.css" rel="stylesheet" />
<h2>Alumno</h2>
<label>Seleccione sexo</label>
<select id="cboSexo">

  
</select>

<div id="tabla">

</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/datatables.min.js"></script>
<script src="~/Scripts/Alumno.js"></script>

MiSegundaAplicacionWeb/Views/Curso/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Curso</h2>


<link href="~/Content/datatables.css" rel="stylesheet" />

<label>Ingrese nombre: </label>
<input type="text" id="txtnombre" />
<input type="button" id="btnBuscar"value="Buscar" class="btn btn-success " />

<input type="button" id="btnLimpiar"value="Limpiar" class="btn btn-success "/>

<div id="tabla">

</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/datatables.min.js"></script>

<script src="~/Scripts/Curso.js"></script>

MiSegundaAplicacionWeb/Views/Periodo/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Periodo</h2>
<link href="~/Content/datatables.css" rel="stylesheet" />

<label>Ingrese nombre: </label>
<input type="text" id="txtnombre" />
<input type="button" id="btnBuscar" value="Buscar" class="btn btn-success " />
<input type="button" id="btnLimpiar" value="Limpiar" class="btn btn-success " />

<div id="tabla">
    
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/Periodo.js"></script>
<script src="~/Scripts/datatables.min.js"></script>

MiSegundaAplicacionWeb/Views/Seccion/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}

<h2>Inicio</h2>

MiSegundaAplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Curso", "Index", "Curso", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Periodo", "Index", "Periodo", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Secciones", "Inicio", "Seccion", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Alumno", "Index", "Alumno", new { area = "" }, new { @class = "navbar-brand" })


            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

   
</body>
</html>